[package]
name = "zkcard_wasm_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[dependencies]
zkcard_wasm = { git = "https://github.com/HyprNetwork/zkcard-mini-sdk.git" }